In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


In [3]:
a = np.array([1, 2, 3])
b = np.zeros((2, 2))
c = np.ones((2, 2))
d = np.arange(0, 10, 2)
e = np.empty((2, 2), dtype=int)

print("Matrix A \n", a, "\n Matrix B \n", b, "\n Matrix C \n", c, "\n Matrix D \n", d, "\n Matrix E \n", e)

Matrix A 
 [1 2 3] 
 Matrix B 
 [[0. 0.]
 [0. 0.]] 
 Matrix C 
 [[1. 1.]
 [1. 1.]] 
 Matrix D 
 [0 2 4 6 8] 
 Matrix E 
 [[25895968444448860 23925768161198147]
 [32370111954616435 27303562374545500]]


In [4]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [11]:
arr = np.array([10, 20, 30, 40])

print("First element:", arr[0])
print("Last element:", arr[-1])

First element: 10
Last element: 40


In [10]:
arr = np.array([10, 20, 30, 40, 50])

print("Slice (1 to 3):", arr[1:4])
print("First three elements:", arr[:3])

Slice (1 to 3): [20 30 40]
First three elements: [10 20 30]


In [9]:
arr = np.array([1, 2, 3])

print("Add scalar:", arr + 5)

b = np.array([[1], [2], [3]])
c = np.array([10, 20, 30])

print("Broadcasting result:\n", b + c)

Add scalar: [6 7 8]
Broadcasting result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [8]:
import pandas as pd

data = [10, 20, 30, 40]
series = pd.Series(data)

print(series)
print("First element:", series[0])

0    10
1    20
2    30
3    40
dtype: int64
First element: 10


In [7]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "A", "B"],
    "Age": [20, 21, 22, 20, 21]
}
df = pd.DataFrame(data)

print("Info:")
print(df.info())

print("\nDescribe:\n", df.describe())

print("\nValue Counts:\n", df["Name"].value_counts())

print("\nHead:\n", df.head())

print("\nTail:\n", df.tail())

Info:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str  
 1   Age     5 non-null      int64
dtypes: int64(1), str(1)
memory usage: 212.0 bytes
None

Describe:
             Age
count   5.00000
mean   20.80000
std     0.83666
min    20.00000
25%    20.00000
50%    21.00000
75%    21.00000
max    22.00000

Value Counts:
 Name
A    2
B    2
C    1
Name: count, dtype: int64

Head:
   Name  Age
0    A   20
1    B   21
2    C   22
3    A   20
4    B   21

Tail:
   Name  Age
0    A   20
1    B   21
2    C   22
3    A   20
4    B   21


In [6]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22]
})

print(df["Name"])      
print(df.iloc[0:2])

0    A
1    B
2    C
Name: Name, dtype: str
  Name  Age
0    A   20
1    B   21


In [5]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [85, 95, 90]
})

print(df.sort_values(by="Marks", ascending=False))

  Name  Marks
1    B     95
2    C     90
0    A     85
