In [4]:
import numpy as np

a = [1, 2, 3, 4]

arr = np.array(a)

print("List in python :", a)
print("Numpy Array in python :", arr)

List in python : [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


In [6]:
import numpy as np

list_1 = [1, 2, 3, 4]

sample_array = np.array(list_1)

print(type(list_1))
print(type(sample_array))


<class 'list'>
<class 'numpy.ndarray'>


In [7]:
import numpy as np

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([
    list_1,
    list_2,
    list_3
])

print("Numpy multi dimensional array in python\n", sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
import numpy as np

sample_array = np.array([
    [0, 4, 2],
    [3, 4, 5],
    [23, 4, 5],
    [2, 34, 5],
    [5, 6, 7]
])

print("shape of the array :", sample_array.shape)


shape of the array : (5, 3)


In [10]:
import numpy as np

sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int64
Data type of array 2 : float64


In [11]:
import numpy as np

arr = np.array([3, 4, 5, 5])

print("Array :", arr)

Array : [3 4 5 5]


In [12]:
import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype='U2')

print("fromiter() array :", arr)


fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [13]:
import numpy as np

arr = np.arange(1, 20, 2, dtype=np.float32)

print(arr)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


In [14]:
import numpy as np

arr = np.linspace(3.5, 10, 3, dtype=np.int32)

print(arr)

[ 3  6 10]


In [ ]:
import numpy as np
np.zeros([4, 3], 
         dtype = np.int32,
         order = 'f')


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)